# Generated by Django 5.2.3 on 2025-06-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
        ('usuarios', '0002_remove_perfilusuario_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposocio',
            options={'default_manager_name': 'objects', 'verbose_name': 'Tipo de Socio', 'verbose_name_plural': 'Tipos de Socios'},
        ),
        migrations.RemoveField(
            model_name='socio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_estado',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='usuario',
        ),
        migrations.AddField(
            model_name='socio',
            name='perfil_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='usuarios.perfilusuario'),
        ),
    ]
