# Generated by Django 5.2.3 on 2025-06-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='estado_socio',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('PENDIENTE', 'Pendiente de Aprobación'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=10, verbose_name='Estado como Socio'),
        ),
    ]
