# Generated by Django 5.2.3 on 2025-06-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0002_alter_tiposocio_options_remove_socio_estado_and_more'),
        ('usuarios', '0002_remove_perfilusuario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(max_length=100)),
                ('cupo_maximo', models.IntegerField()),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_coordinadas', to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias', models.ManyToManyField(related_name='horarios', to='disciplinas.dia')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('perfil_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cupo_maximo', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='disciplinas.disciplina')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disciplinas.horario')),
                ('profesores', models.ManyToManyField(related_name='categorias', to='disciplinas.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='disciplinas.categoria')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='socios.socio')),
            ],
            options={
                'unique_together': {('socio', 'categoria')},
            },
        ),
    ]
