# Generated by Django 5.2.3 on 2025-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('usuarios', '0002_remove_perfilusuario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='profesores',
            field=models.ManyToManyField(related_name='categorias', to='usuarios.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
