# Generated by Django 5.2.3 on 2025-06-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_categoria_especialidad_alter_categoria_profesores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='cupo_maximo',
        ),
    ]
